version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "<TASK_DEFINITION_PLACEHOLDER>"
        LoadBalancerInfo:
          ContainerName: "simple-app"
          ContainerPort: 80
